name: TACCO_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>3.7.0,!=3.8.0
  - requests
  - joblib
  - numba>=0.51.2
  - numpy
  - matplotlib!=3.7.0
  - pyqt!=5.9.2
  - seaborn
  - sparse_dot_mkl>=0.7.3
  - scanpy>=1.7.0
  - statsmodels
  - anndata
  - pandas>=1.1.0
  - scipy>=1.6.0
  - mkl
  - mkl-service
  - scikit-learn
  - threadpoolctl
  - pyamg
  - tacco

